--------------------------------------------------------------------------------
-- RBAC setup for the OLS Dashboard
--   * ols_users        : EXISTING table (identity + base role) — NOT created here,
--                        only READ. We rely on these columns:
--                          USERNAME, FIRSTNAME, LASTNAME, EMAILID,
--                          LGCL_DEL_FLG ('N' = active),
--                          IS_ADMIN, IS_READ, IS_SALT  ('Y'/'N')
--   * ols_app_access   : NEW table (this script) — the fine-grained override grants.
--
-- Model & cookbook: see RBAC_DESIGN.md. Grant = INSERT a row; revoke = set IS_ACTIVE='N'.
-- Run as the schema owner of the app tables. Adjust the schema/tablespace as needed.
--------------------------------------------------------------------------------

-- 1) (Reference only) confirm the base-role columns exist on ols_users. If any are
--    missing in your instance, add them (Y/N flags); do NOT drop/recreate ols_users.
--    ALTER TABLE ols_users ADD (is_admin CHAR(1) DEFAULT 'N', is_read CHAR(1) DEFAULT 'N', is_salt CHAR(1) DEFAULT 'N');

--------------------------------------------------------------------------------
-- 2) The grants table
--------------------------------------------------------------------------------
CREATE TABLE ols_app_access (
  access_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,          -- surrogate PK
  username       VARCHAR2(64)  NOT NULL,                            -- matches ols_users.username (case-insensitive)
  resource_type  VARCHAR2(20)  NOT NULL,                            -- SCREEN | SERVER | APP | DB | TABLE_CATEGORY | TABLE | SECTION
  resource_scope VARCHAR2(64)  NOT NULL,                            -- log_analytics | infra_health | config_ops:group|cib|retail | service_console | oracle_command_center
  resource_key   VARCHAR2(128) DEFAULT '*' NOT NULL,               -- server | app(OLS_GROUP…) | db(group,cib_batch…) | table | category | section | '*'
  access_level   VARCHAR2(10)  NOT NULL,                            -- READ | WRITE | DENY
  app_env        VARCHAR2(10)  DEFAULT 'PROD' NOT NULL,             -- PROD | STG | DEV | '*' (all envs)
  is_active      CHAR(1)       DEFAULT 'Y' NOT NULL,                -- Y active, N revoked (kept for audit)
  granted_by     VARCHAR2(64),
  granted_on     DATE          DEFAULT SYSDATE,
  comments       VARCHAR2(400),
  CONSTRAINT ols_app_access_pk   PRIMARY KEY (access_id),
  CONSTRAINT ols_app_access_ck_type  CHECK (resource_type IN ('SCREEN','SERVER','APP','DB','TABLE_CATEGORY','TABLE','SECTION')),
  CONSTRAINT ols_app_access_ck_level CHECK (access_level  IN ('READ','WRITE','DENY')),
  CONSTRAINT ols_app_access_ck_act   CHECK (is_active     IN ('Y','N'))
);

-- Prevent duplicate grants for the same user/resource/env.
CREATE UNIQUE INDEX ols_app_access_uq
  ON ols_app_access (UPPER(username), resource_type, resource_scope, UPPER(resource_key), app_env);

-- Fast lookup for the /api/access/me snapshot.
CREATE INDEX ols_app_access_ix_user ON ols_app_access (UPPER(username), is_active);

COMMENT ON TABLE  ols_app_access                IS 'RBAC override grants for the OLS Dashboard (see RBAC_DESIGN.md).';
COMMENT ON COLUMN ols_app_access.resource_type  IS 'SCREEN | SERVER | APP | DB | TABLE_CATEGORY | TABLE | SECTION';
COMMENT ON COLUMN ols_app_access.resource_scope IS 'log_analytics | config_ops:group|cib|retail | infra_health | service_console | oracle_command_center[:<db>]';
COMMENT ON COLUMN ols_app_access.access_level    IS 'READ | WRITE | DENY (DENY subtracts / excludes; per-table wins over category; SERVER/APP/DB DENY = "all EXCEPT")';

--------------------------------------------------------------------------------
-- 3) Sample grants (edit usernames / envs to taste, then COMMIT)
--    NOTE: ADMIN users need NO rows here — set IS_ADMIN='Y' on ols_users and they
--          get everything. These rows are only for READ / SALT users.
--------------------------------------------------------------------------------

-- READ user JDOE ------------------------------------------------------------
-- Log Analytics: only server eurv15
INSERT INTO ols_app_access (username, resource_type, resource_scope, resource_key, access_level, app_env, granted_by, comments)
VALUES ('JDOE','SERVER','log_analytics','eurv15','READ','PROD','ADMIN1','log access to one server');
-- Config Ops (Group): all FUNCTIONAL tables, read
INSERT INTO ols_app_access (username, resource_type, resource_scope, resource_key, access_level, app_env, granted_by, comments)
VALUES ('JDOE','TABLE_CATEGORY','config_ops:group','OMT-FUNCTIONAL','READ','PROD','ADMIN1','all functional group tables');
-- Config Ops (Group): write ONE table
INSERT INTO ols_app_access (username, resource_type, resource_scope, resource_key, access_level, app_env, granted_by, comments)
VALUES ('JDOE','TABLE','config_ops:group','GRP_COST_CENTER','WRITE','PROD','ADMIN1','edit cost centre');
-- Config Ops (Group): explicitly hide one table the category granted
INSERT INTO ols_app_access (username, resource_type, resource_scope, resource_key, access_level, app_env, granted_by, comments)
VALUES ('JDOE','TABLE','config_ops:group','GRP_GL_MAPPING','DENY','PROD','ADMIN1','not for this user');
-- Oracle Command Center: hide the SQL Intelligence section
INSERT INTO ols_app_access (username, resource_type, resource_scope, resource_key, access_level, app_env, granted_by, comments)
VALUES ('JDOE','SECTION','oracle_command_center','sql_intelligence','DENY','PROD','ADMIN1','hide SQL Intelligence');

-- READ user DBAUSER (a DBA who can act) -------------------------------------
INSERT INTO ols_app_access (username, resource_type, resource_scope, resource_key, access_level, app_env, granted_by, comments)
VALUES ('DBAUSER','SCREEN','service_console','*','WRITE','PROD','ADMIN1','can start/stop services');
INSERT INTO ols_app_access (username, resource_type, resource_scope, resource_key, access_level, app_env, granted_by, comments)
VALUES ('DBAUSER','SERVER','log_analytics','*','READ','PROD','ADMIN1','all log servers');
-- Infra Health, per APP (keys: OLS_GROUP | OLS_CIB | OLS_RETAIL | POSEIDON; '*' = all apps)
INSERT INTO ols_app_access (username, resource_type, resource_scope, resource_key, access_level, app_env, granted_by, comments)
VALUES ('DBAUSER','APP','infra_health','OLS_GROUP','READ','PROD','ADMIN1','Infra Health: only OLS_GROUP');
-- Oracle Command Center, per DB + per-DB level (keys: group | cib_batch | cib_reporting |
-- retail_batch | retail_reporting; '*' = all DBs). WRITE = kill/apply on that DB, READ = view only.
INSERT INTO ols_app_access (username, resource_type, resource_scope, resource_key, access_level, app_env, granted_by, comments)
VALUES ('DBAUSER','DB','oracle_command_center','group','WRITE','PROD','ADMIN1','OCC: write to GROUP');
INSERT INTO ols_app_access (username, resource_type, resource_scope, resource_key, access_level, app_env, granted_by, comments)
VALUES ('DBAUSER','DB','oracle_command_center','cib_batch','READ','PROD','ADMIN1','OCC: read-only CIB BATCH');

-- SALT user BOB (IS_SALT='Y' on ols_users) : Config-Ops-only, a few CIB tables -
INSERT INTO ols_app_access (username, resource_type, resource_scope, resource_key, access_level, app_env, granted_by, comments)
VALUES ('BOB','TABLE','config_ops:cib','CIB_LIMIT_CONFIG','READ','PROD','ADMIN1','salt user table access');
INSERT INTO ols_app_access (username, resource_type, resource_scope, resource_key, access_level, app_env, granted_by, comments)
VALUES ('BOB','TABLE','config_ops:cib','CIB_FX_RATES','READ','PROD','ADMIN1','salt user table access');

COMMIT;

--------------------------------------------------------------------------------
-- 4) Handy management statements
--------------------------------------------------------------------------------
-- Revoke a grant (keep the audit row):
--   UPDATE ols_app_access SET is_active='N' WHERE username='JDOE' AND resource_type='SERVER' AND resource_key='eurv15';  COMMIT;
--
-- See everything a user has:
--   SELECT resource_type, resource_scope, resource_key, access_level, app_env, is_active
--     FROM ols_app_access WHERE UPPER(username)=UPPER('JDOE') ORDER BY resource_type, resource_scope;
--
-- Grant a whole category (bulk) vs one table:
--   ...TABLE_CATEGORY / config_ops:cib / OMT-BOTH / READ    -> every CIB table
--   ...TABLE          / config_ops:cib / CIB_SWIFT_MAPPING / WRITE
--------------------------------------------------------------------------------
