--------------------------------------------------------------------------------
-- OLS Dashboard — DATA RECONCILIATION tables
--
-- Post-regression (and ad-hoc) validation: run business reports on a LIVE db + a Regression db,
-- then compare the aggregate output; any mismatch is a red flag. Phase 1 covers TRIGGER + EXTRACT
-- MONITORING (comparison + results land in Phase 2). Used only in DEV/STG.
--
--   * ols_recon_report_config — the report catalogue (per scope DB); drives the report dropdown
--     and (Phase 2) the compare engine. NOTHING hardcoded — add a row = a new report.
--   * ols_recon_run           — one reconciliation run (LIVE db + Regression db + business date,
--                               optionally linked to a regression run).
--   * ols_recon_extract       — the two batches (LIVE + REG) triggered per report, each carrying its
--                               unique job_run_no (the correlation key polled against the batch monitor).
--------------------------------------------------------------------------------
SET DEFINE OFF;

-- Report catalogue (per scope DB — the connected DB decides the scope, so no scope column) ----------
CREATE TABLE ols_recon_report_config (
  report_code      VARCHAR2(64)  NOT NULL,               -- stable id (dropdown value)
  report_name      VARCHAR2(200) NOT NULL,               -- display name
  category         VARCHAR2(64),                         -- top-level group in the report dropdown (e.g. ALMT, CB)
  sub_category     VARCHAR2(64),                         -- optional nested group (e.g. Activity, StdBs)
  trigger_proc     VARCHAR2(400) NOT NULL,               -- PL/SQL to run the batch, e.g. recon_pkg.run_report
  output_mode      VARCHAR2(10)  DEFAULT 'FILE' NOT NULL, -- FILE | TABLE (where the batch writes its output)
  key_columns      VARCHAR2(1000),                       -- comma-separated join keys (Phase 2 compare)
  measure_columns  VARCHAR2(1000),                       -- comma-separated numeric columns to compare (Phase 2)
  tolerance_type   VARCHAR2(10)  DEFAULT 'EXACT',        -- EXACT | ABS | PCT (Phase 2)
  tolerance_value  NUMBER        DEFAULT 0,
  is_active        CHAR(1)       DEFAULT 'Y' NOT NULL,    -- Y = shown in the dropdown
  sort_order       NUMBER        DEFAULT 100,
  extra_config     CLOB,                                 -- JSON catch-all for anything else a report needs
  CONSTRAINT ols_recon_report_config_pk PRIMARY KEY (report_code)
);

-- One reconciliation run ----------------------------------------------------------------------------
CREATE TABLE ols_recon_run (
  load_dt         DATE          DEFAULT SYSDATE NOT NULL,   -- activity date
  run_id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
  app_env         VARCHAR2(10)  NOT NULL,                   -- DEV | STG
  scope           VARCHAR2(20)  NOT NULL,                   -- group | cib | retail
  live_db         VARCHAR2(64)  NOT NULL,                   -- selected LIVE db (e.g. OLSCD1)
  regression_db   VARCHAR2(64)  NOT NULL,                   -- selected Regression db
  business_date   VARCHAR2(8)   NOT NULL,                   -- YYYYMMDD the batch runs for
  regression_run_id NUMBER,                                 -- optional link to ols_regression_run
  change_number   VARCHAR2(50),                             -- carried from the linked regression run
  release_date    VARCHAR2(8),                              -- carried from the linked regression run
  status          VARCHAR2(20)  DEFAULT 'running' NOT NULL, -- running | complete (all extracts settled)
  triggered_by    VARCHAR2(64)  NOT NULL,
  triggered_on    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ols_recon_run_pk PRIMARY KEY (run_id)
);

-- The two extract batches (LIVE + REG) per report in a run -------------------------------------------
CREATE TABLE ols_recon_extract (
  load_dt       DATE          DEFAULT SYSDATE NOT NULL,
  extract_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
  run_id        NUMBER        NOT NULL,
  report_code   VARCHAR2(64)  NOT NULL,
  side          VARCHAR2(4)   NOT NULL,                     -- LIVE | REG
  db_source     VARCHAR2(64)  NOT NULL,                     -- the db the batch ran against (OLSCD1…)
  job_run_no    VARCHAR2(64),                               -- unique per batch — the poll correlation key
  status        VARCHAR2(20)  DEFAULT 'queued' NOT NULL,    -- queued | running | done | no_data | failed
  message       VARCHAR2(2000),                             -- last status detail / error text
  start_time    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  end_time      TIMESTAMP,
  CONSTRAINT ols_recon_extract_pk PRIMARY KEY (extract_id),
  CONSTRAINT ols_recon_extract_fk FOREIGN KEY (run_id) REFERENCES ols_recon_run (run_id)
);

CREATE INDEX ols_recon_extract_run_ix ON ols_recon_extract (run_id);
CREATE INDEX ols_recon_extract_job_ix ON ols_recon_extract (job_run_no);

-- Comparison result per report (Phase 2) — the summary + the full discrepancy grid (as JSON) ---------
CREATE TABLE ols_recon_result (
  load_dt       DATE          DEFAULT SYSDATE NOT NULL,
  result_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
  run_id        NUMBER        NOT NULL,
  report_code   VARCHAR2(64)  NOT NULL,
  status        VARCHAR2(10)  NOT NULL,                     -- PASS | FAIL
  matched       NUMBER        DEFAULT 0,
  changed       NUMBER        DEFAULT 0,                    -- key in both, a measure differs
  missing       NUMBER        DEFAULT 0,                    -- key only in LIVE (missing in Regression)
  extra         NUMBER        DEFAULT 0,                    -- key only in Regression
  compared      NUMBER        DEFAULT 0,                    -- total rows compared
  detail_json   CLOB,                                       -- {columns:[...], rows:[[...]]} — the drill-down grid (capped)
  compared_by   VARCHAR2(64),
  compared_on   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ols_recon_result_pk PRIMARY KEY (result_id),
  CONSTRAINT ols_recon_result_uk UNIQUE (run_id, report_code),
  CONSTRAINT ols_recon_result_fk FOREIGN KEY (run_id) REFERENCES ols_recon_run (run_id)
);

--------------------------------------------------------------------------------
-- SAMPLE DATA (DML) — edit report_code / names / trigger_proc / columns for YOUR reports, then run.
-- The dropdown groups by CATEGORY (one dropdown per category) then SUB_CATEGORY. Reports with no
-- sub_category list flat under their category. trigger_proc is the PL/SQL that runs the batch (must
-- return a unique job_run_no). This is illustrative — replace with your real catalogue.
--------------------------------------------------------------------------------
INSERT INTO ols_recon_report_config (report_code, report_name, category, sub_category, trigger_proc, output_mode, key_columns, measure_columns, tolerance_type, tolerance_value, sort_order)
  VALUES ('ALMT_ACT_PNL',  'P&L Aggregate',      'ALMT', 'Activity', 'recon_pkg.run_report', 'FILE',  'LMA_CODE,CPT_CODE,AMOUNT_CODE', 'AMOUNT', 'EXACT', 0, 10);
INSERT INTO ols_recon_report_config (report_code, report_name, category, sub_category, trigger_proc, output_mode, key_columns, measure_columns, tolerance_type, tolerance_value, sort_order)
  VALUES ('ALMT_ACT_POS',  'Positions',          'ALMT', 'Activity', 'recon_pkg.run_report', 'TABLE', 'LMA_CODE,CPT_CODE',            'AMOUNT', 'EXACT', 0, 20);
INSERT INTO ols_recon_report_config (report_code, report_name, category, sub_category, trigger_proc, output_mode, key_columns, measure_columns, tolerance_type, tolerance_value, sort_order)
  VALUES ('ALMT_STD_BAL',  'Balances',           'ALMT', 'StdBs',    'recon_pkg.run_report', 'FILE',  'LMA_CODE',                     'AMOUNT', 'EXACT', 0, 30);
INSERT INTO ols_recon_report_config (report_code, report_name, category, sub_category, trigger_proc, output_mode, key_columns, measure_columns, tolerance_type, tolerance_value, sort_order)
  VALUES ('ALMT_STD_FEES', 'Fees Summary',       'ALMT', 'StdBs',    'recon_pkg.run_report', 'FILE',  'CPT_CODE,AMOUNT_CODE',         'AMOUNT', 'EXACT', 0, 40);
INSERT INTO ols_recon_report_config (report_code, report_name, category, sub_category, trigger_proc, output_mode, key_columns, measure_columns, tolerance_type, tolerance_value, sort_order)
  VALUES ('CB_RISK',       'Risk Exposure',      'CB',   NULL,       'recon_pkg.run_report', 'TABLE', 'LMA_CODE,CPT_CODE,AMOUNT_CODE', 'AMOUNT', 'ABS',   1, 50);
INSERT INTO ols_recon_report_config (report_code, report_name, category, sub_category, trigger_proc, output_mode, key_columns, measure_columns, tolerance_type, tolerance_value, sort_order)
  VALUES ('CB_LIQ',        'Liquidity Summary',  'CB',   NULL,       'recon_pkg.run_report', 'FILE',  'LMA_CODE,CPT_CODE',            'AMOUNT', 'EXACT', 0, 60);
COMMIT;
