--------------------------------------------------------------------------------
-- OLS Dashboard — REGRESSION screen tables (ols_regression_run + ols_regression_log)
--
-- Drives + audits the pre-prod regression cycle (Refresh DB → Apply DB changes → File copy →
-- Reset batches → Trigger batches → Monitor). Every step action is logged: who, what, when it
-- started, when it finished, and how long it took. Used only in DEV/STG.
--
--   * A RUN groups one regression cycle. Steps + actions are LOG rows under a run.
--   * `status`: not_started | in_progress | complete | error | forced.
--   * `forced_by` is set when a step was force-marked complete (skip-gate override).
--------------------------------------------------------------------------------
SET DEFINE OFF;

CREATE TABLE ols_regression_run (
  run_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
  app_env     VARCHAR2(10)  NOT NULL,                 -- DEV | STG
  status      VARCHAR2(20)  DEFAULT 'in_progress' NOT NULL,
  started_by  VARCHAR2(64)  NOT NULL,
  started_on  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  finished_on TIMESTAMP,
  CONSTRAINT ols_regression_run_pk PRIMARY KEY (run_id)
);

CREATE TABLE ols_regression_log (
  log_id               NUMBER GENERATED BY DEFAULT AS IDENTITY,
  run_id               NUMBER        NOT NULL,
  business_line        VARCHAR2(64),                  -- nullable: set for per-line trigger/monitor
  step_key             VARCHAR2(40)  NOT NULL,        -- refresh_db | apply_db | file_copy | reset | trigger | ...
  action               VARCHAR2(64)  NOT NULL,        -- start | complete | error | forced | run_sql | copy | ...
  status               VARCHAR2(20)  NOT NULL,        -- in_progress | complete | error | forced
  performed_by         VARCHAR2(64)  NOT NULL,
  started_on           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  finished_on          TIMESTAMP,
  task_completion_time NUMBER,                        -- elapsed seconds (finished_on - started_on)
  forced_by            VARCHAR2(64),                  -- set when force-marked complete
  details              CLOB,                          -- scripts+DBs, files copied, rows affected, ORA errors, log path
  CONSTRAINT ols_regression_log_pk PRIMARY KEY (log_id),
  CONSTRAINT ols_regression_log_fk FOREIGN KEY (run_id) REFERENCES ols_regression_run (run_id)
);

CREATE INDEX ols_regression_log_ix ON ols_regression_log (run_id, step_key);

COMMENT ON TABLE  ols_regression_run  IS 'One regression cycle (DEV/STG). See RBAC_DESIGN.md / Regression screen.';
COMMENT ON TABLE  ols_regression_log  IS 'Per-action audit for a regression run: who/what/when-started/when-finished/duration.';
COMMENT ON COLUMN ols_regression_log.task_completion_time IS 'Elapsed seconds = finished_on - started_on.';
COMMENT ON COLUMN ols_regression_log.details IS 'What was done: scripts+DBs, files copied, rows affected, ORA errors, force notes, log-file path.';
