--------------------------------------------------------------------------------
-- OLS Dashboard — REGRESSION screen tables (ols_regression_run + ols_regression_log)
--
-- Drives + audits the pre-prod regression cycle (Refresh DB → Apply DB changes → File copy →
-- Reset batches → Trigger batches → Monitor). Every step action is logged: who, what, when it
-- started, when it finished, and how long it took. Used only in DEV/STG.
--
--   * A RUN groups one regression cycle. Steps + actions are LOG rows under a run.
--   * `status`: not_started | in_progress | complete | error | forced.
--   * `forced_by` is set when a step was force-marked complete (skip-gate override).
--------------------------------------------------------------------------------
SET DEFINE OFF;

CREATE TABLE ols_regression_run (
  load_dt     DATE          DEFAULT SYSDATE NOT NULL, -- activity date (query "today's/yesterday's" runs)
  run_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
  app_env     VARCHAR2(10)  NOT NULL,                 -- DEV | STG
  status      VARCHAR2(20)  DEFAULT 'in_progress' NOT NULL,
  started_by  VARCHAR2(64)  NOT NULL,
  git_branch    VARCHAR2(160),                       -- the release/* branch this run pulled + applied
  release_date  VARCHAR2(8),                          -- YYYYMMDD release folder (WHICH release we regressed)
  change_number VARCHAR2(50),                         -- Change (CHG) number this regression run is tagged to
  start_time  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,   -- run start
  end_time    TIMESTAMP,                                     -- run finish
  CONSTRAINT ols_regression_run_pk PRIMARY KEY (run_id)
);

CREATE TABLE ols_regression_log (
  load_dt              DATE          DEFAULT SYSDATE NOT NULL, -- activity date (query by log_id | run_id | load_dt)
  log_id               NUMBER GENERATED BY DEFAULT AS IDENTITY,
  run_id               NUMBER        NOT NULL,
  business_line        VARCHAR2(64),                  -- nullable: set for per-line trigger/monitor
  step_key             VARCHAR2(40)  NOT NULL,        -- refresh_db | apply_db | file_copy | reset | trigger | ...
  action               VARCHAR2(64)  NOT NULL,        -- start | complete | error | forced | run_sql | copy | ...
  status               VARCHAR2(20)  NOT NULL,        -- in_progress | complete | error | forced
  performed_by         VARCHAR2(64)  NOT NULL,
  start_time           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,   -- step/action start
  end_time             TIMESTAMP,                                     -- step/action finish
  task_completion_time NUMBER,                        -- elapsed seconds (end_time - start_time)
  forced_by            VARCHAR2(64),                  -- set when force-marked complete
  comments             CLOB,                          -- scripts+DBs, files copied, rows affected, ORA errors, log path
  CONSTRAINT ols_regression_log_pk PRIMARY KEY (log_id),
  CONSTRAINT ols_regression_log_fk FOREIGN KEY (run_id) REFERENCES ols_regression_run (run_id)
);

CREATE INDEX ols_regression_log_ix ON ols_regression_log (run_id, step_key);

COMMENT ON TABLE  ols_regression_run  IS 'One regression cycle (DEV/STG). See RBAC_DESIGN.md / Regression screen.';
COMMENT ON TABLE  ols_regression_log  IS 'Per-action audit for a regression run: who/what/when-started/when-finished/duration.';
COMMENT ON COLUMN ols_regression_log.task_completion_time IS 'Elapsed seconds = end_time - start_time.';
COMMENT ON COLUMN ols_regression_log.comments IS 'What was done: scripts+DBs, files copied, rows affected, ORA errors, force notes, log-file path.';
COMMENT ON COLUMN ols_regression_run.git_branch   IS 'release/* branch this run pulled + applied.';
COMMENT ON COLUMN ols_regression_run.release_date IS 'YYYYMMDD release folder — which release this regression cycle targeted (distinguishes 2 releases in a month).';
COMMENT ON COLUMN ols_regression_run.change_number IS 'Change (CHG) number this regression run is tagged to (one CHG per release; a CHG may have >1 run).';

--------------------------------------------------------------------------------
-- Migration — add git_branch / release_date to an EXISTING ols_regression_run (safe to re-run;
-- ORA-01430 = "column already exists" is swallowed so the script is idempotent).
--------------------------------------------------------------------------------
DECLARE
  PROCEDURE add_col(p_sql IN VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;   -- ignore "column already exists"
  END;
BEGIN
  add_col('ALTER TABLE ols_regression_run ADD (git_branch VARCHAR2(160))');
  add_col('ALTER TABLE ols_regression_run ADD (release_date VARCHAR2(8))');
  add_col('ALTER TABLE ols_regression_run ADD (change_number VARCHAR2(50))');
END;
/
