--------------------------------------------------------------------------------
-- OLS Dashboard — Config Ops CSV Upload & Load tables
--
-- ols_upload_audit : one row per load attempt (success/partial/failed) — who / when / which table /
--                    which date / which file (NAS path + SHA-256) / rows in-loaded-rejected-deleted.
-- ols_upload_lock  : per-target serialization row; the load takes SELECT ... FOR UPDATE NOWAIT on it
--                    so two operators can't load the same table (or table+date) at once. The lock
--                    auto-releases at commit/rollback. See UPLOAD_DESIGN.md.
--------------------------------------------------------------------------------
SET DEFINE OFF;

CREATE TABLE ols_upload_audit (
  load_id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
  app_env            VARCHAR2(10),
  scope              VARCHAR2(20),
  table_name         VARCHAR2(128)  NOT NULL,
  load_mode          VARCHAR2(20)   NOT NULL,          -- append | replace
  date_col           VARCHAR2(128),                    -- COB_DT / REPORTING_DT (null for non-date tables)
  cob_dt             VARCHAR2(30),                     -- the single load date (null for non-date tables)
  original_filename  VARCHAR2(512),
  archived_path      VARCHAR2(1024),                   -- NAS path of the copied file
  file_hash          VARCHAR2(64),                     -- SHA-256 of the loaded CSV
  delimiter          VARCHAR2(10),
  uploaded_by        VARCHAR2(64)   NOT NULL,
  uploaded_on        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  finished_on        TIMESTAMP,
  duration_secs      NUMBER,
  rows_in_file       NUMBER,
  rows_loaded        NUMBER,
  rows_rejected      NUMBER,
  rows_deleted       NUMBER,
  status             VARCHAR2(20),                     -- success | partial | failed
  error_detail       CLOB,
  CONSTRAINT ols_upload_audit_pk PRIMARY KEY (load_id)
);

CREATE INDEX ols_upload_audit_ix ON ols_upload_audit (table_name, uploaded_on);

CREATE TABLE ols_upload_lock (
  lock_key    VARCHAR2(400) NOT NULL,                  -- scope|table  (or scope|table|cob_dt)
  locked_by   VARCHAR2(64),
  locked_on   TIMESTAMP,
  CONSTRAINT ols_upload_lock_pk PRIMARY KEY (lock_key)
);

COMMENT ON TABLE  ols_upload_audit IS 'Per-load audit for Config Ops CSV upload. See UPLOAD_DESIGN.md.';
COMMENT ON TABLE  ols_upload_lock  IS 'Serialization rows for concurrent config uploads (SELECT FOR UPDATE NOWAIT).';

--------------------------------------------------------------------------------
-- The date-column mapping is the CUSTOMER's existing 1-1 table (table_name -> date column, e.g.
-- COB_DT / REPORTING_DT). Point CONFIG_DATE_MAP_TABLE / _KEY_COL / _DATE_COL at it in .env. Expected
-- shape (example only — do NOT create if you already have it):
--   -- CREATE TABLE ols_table_date_map (table_name VARCHAR2(128) PRIMARY KEY, date_col VARCHAR2(128));
--------------------------------------------------------------------------------
