--------------------------------------------------------------------------------
-- OLS Dashboard — Config Ops CSV Upload & Load tables
--
-- ols_upload_audit : one row per load attempt (success/partial/failed) — who / when / which table /
--                    which date / which file (NAS path + SHA-256) / rows in-loaded-rejected-deleted.
-- ols_upload_lock  : per-target serialization row; the load takes SELECT ... FOR UPDATE NOWAIT on it
--                    so two operators can't load the same table (or table+date) at once. The lock
--                    auto-releases at commit/rollback. See GUIDE.md (Config Ops CSV Upload & Load).
--------------------------------------------------------------------------------
SET DEFINE OFF;

CREATE TABLE ols_upload_audit (
  load_id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
  load_dt            DATE DEFAULT SYSDATE NOT NULL,    -- activity date (query "today's/yesterday's" loads)
  app_env            VARCHAR2(10),
  scope              VARCHAR2(20),
  table_name         VARCHAR2(128)  NOT NULL,
  load_mode          VARCHAR2(20)   NOT NULL,          -- append | replace
  date_col           VARCHAR2(128),                    -- COB_DT / REPORTING_DT (null for non-date tables)
  cob_dt             VARCHAR2(30),                     -- the single business date loaded (null for non-date tables)
  original_filename  VARCHAR2(512),
  archived_path      VARCHAR2(1024),                   -- NAS path of the copied file
  file_hash          VARCHAR2(64),                     -- SHA-256 of the loaded CSV
  delimiter          VARCHAR2(10),
  uploaded_by        VARCHAR2(64)   NOT NULL,
  start_time         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,   -- load start
  end_time           TIMESTAMP,                                 -- load finish
  duration_secs      NUMBER,                           -- end_time - start_time, seconds (convenience)
  rows_in_file       NUMBER,
  rows_loaded        NUMBER,
  rows_rejected      NUMBER,
  rows_deleted       NUMBER,
  status             VARCHAR2(20),                     -- success | partial | failed
  error_desc         CLOB,
  CONSTRAINT ols_upload_audit_pk PRIMARY KEY (load_id)
);

CREATE INDEX ols_upload_audit_ix ON ols_upload_audit (table_name, start_time);

CREATE TABLE ols_upload_lock (
  lock_key    VARCHAR2(400) NOT NULL,                  -- scope|table  (or scope|table|cob_dt)
  locked_by   VARCHAR2(64),
  locked_on   TIMESTAMP,
  CONSTRAINT ols_upload_lock_pk PRIMARY KEY (lock_key)
);

COMMENT ON TABLE  ols_upload_audit IS 'Per-load audit for Config Ops CSV upload. See GUIDE.md.';
COMMENT ON TABLE  ols_upload_lock  IS 'Serialization rows for concurrent config uploads (SELECT FOR UPDATE NOWAIT).';

--------------------------------------------------------------------------------
-- Audit-write procedure. The DB owns the ols_upload_audit column list (the app just calls this via
-- cursor.callproc), so a schema change here needs no app redeploy. PRAGMA AUTONOMOUS_TRANSACTION →
-- the audit row COMMITs in its own transaction, so a load that ROLLBACKs is still audited. Returns
-- the generated load_id via the OUT param. (Move it into a package if you prefer; keep the name/args.)
--------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE ols_upload_audit_write (
  p_app_env            IN  VARCHAR2,
  p_scope              IN  VARCHAR2,
  p_table_name         IN  VARCHAR2,
  p_load_mode          IN  VARCHAR2,
  p_date_col           IN  VARCHAR2,
  p_cob_dt             IN  VARCHAR2,
  p_original_filename  IN  VARCHAR2,
  p_archived_path      IN  VARCHAR2,
  p_file_hash          IN  VARCHAR2,
  p_delimiter          IN  VARCHAR2,
  p_uploaded_by        IN  VARCHAR2,
  p_start_time         IN  TIMESTAMP,
  p_end_time           IN  TIMESTAMP,
  p_duration_secs      IN  NUMBER,
  p_rows_in_file       IN  NUMBER,
  p_rows_loaded        IN  NUMBER,
  p_rows_rejected      IN  NUMBER,
  p_rows_deleted       IN  NUMBER,
  p_status             IN  VARCHAR2,
  p_error_desc         IN  CLOB,
  p_load_id            OUT NUMBER
) AS
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  -- load_dt defaults to SYSDATE; not set here.
  INSERT INTO ols_upload_audit (
    app_env, scope, table_name, load_mode, date_col, cob_dt, original_filename,
    archived_path, file_hash, delimiter, uploaded_by, start_time, end_time,
    duration_secs, rows_in_file, rows_loaded, rows_rejected, rows_deleted, status, error_desc
  ) VALUES (
    p_app_env, p_scope, p_table_name, p_load_mode, p_date_col, p_cob_dt, p_original_filename,
    p_archived_path, p_file_hash, p_delimiter, p_uploaded_by, COALESCE(p_start_time, SYSTIMESTAMP),
    p_end_time, p_duration_secs, p_rows_in_file, p_rows_loaded, p_rows_rejected, p_rows_deleted,
    p_status, p_error_desc
  ) RETURNING load_id INTO p_load_id;
  COMMIT;
END;
/

--------------------------------------------------------------------------------
-- The date column per table comes from the CUSTOMER's existing DB function
-- ols_util.get_date_column(<table_name>) -> 'COB_DT' / 'REPORTING_DT'. The backend calls it via
-- cursor.callfunc and defaults to COB_DT when it returns nothing. No mapping table is created here.
--------------------------------------------------------------------------------
